describe("new", function()
    describe("thread.new", function()
        local thread_new = require("resty.thread.new")
        it("hello", function()
            local th = thread_new.new("testpool")
            assert(th)
            local s, err = th:run(function(d)
                return d
            end, "hello")
            assert.is_equal(s, 'hello', err)
        end)
        it("invaild threadpool", function()
            local th, err = thread_new.new("test")
            assert.is_nil(th, err)
        end)
    end)
end)
