local th = require "resty.thread"
describe("resty.thread", function()
    describe("run", function()
        it("hello", function()
            local ok, s = th.run('testpool', function(d)
                return d
            end, "hello")
            assert.is_true(ok)
            assert.is_equal(s, 'hello')
        end)
        it("should be function", function()
            local ok, err = th.run('testpool', 'dd')
            assert.is_false(ok)
            assert.is_equal(err, "fn is not a function")
        end)
        it('should not have up values', function()
            local ok, err = th.run('testpool', function(d)
                return th.run
            end)
            assert.is_false(ok)
            assert.is_equal(err, "fn must not have up values:1")
        end)
    end)
end)
